# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in jekyll.gemspec
gemspec

gem "rake", "~> 13.0"
gem "jekyll", "~> 04.03.03"
gem "gosu", "~> 1.4.6"
gem  "dotenv"
gem "github-pages"
gem "jekyll-github-metadata"
