# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in jekyll.gemspec
gemspec

gem "rake", "~> 13.0"
gem "github-pages"
gem "jekyll"
gem "jekyll-github-metadata"
gem "gosu"